name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          aws-region: eu-west-2
          role-to-assume: arn:aws:iam::094954420758:role/github-cdp-example-node-backend-build-role
      - run: aws sts get-caller-identity
        shell: bash
      - run: aws secretsmanager get-secret-value --secret-id cdp/services/sc-test-1 | jq '.SecretString = "***"'
        shell: bash
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run format:check
      - run: npm run lint
      - run: npm test
      # No longer needed with the latest version of the SonarCloud GitHub Action
      # https://community.sonarsource.com/t/code-coverage-doesnt-work-with-github-action/16747/6
      # - name: make sonar aware of coverage tests path
      #   run: sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage/lcov.info
      - name: SonarCloud Scan
        if: github.actor != 'dependabot[bot]'
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
