name: Check Pull Request

on:
  pull_request:
    branches:
      - main
    types:
      - opened
      - edited
      - reopened
      - synchronize
      - ready_for_review

jobs:
  pr-validator:
    name: Run Pull Request Checks
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: npm
      - run: npm install
      - run: npm run format:check
      - run: npm run lint
      - run: npm test
      # # https://community.sonarsource.com/t/code-coverage-doesnt-work-with-github-action/16747/6
      # - name: Run unit tests
      #   run: |
      #     npm test
      #     sed -i 's@'$GITHUB_WORKSPACE'@/github/workspace/@g' coverage/lcov.info
      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
